---
title: "Houston Models"
author: "Andrew Maloney"
date: "1/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
#Group 1
library(caret)
set.seed(20140501)
inTraining_p <- createDataPartition(f2_1$samesource, p = .80, list = FALSE)
training_p <- f2_1[ inTraining_p,]
testing_p  <- f2_1[-inTraining_p,]
```

```{r}
#Group 2
set.seed(20140501)
inTraining_p_2 <- createDataPartition(f2_2$samesource, p = .80, list = FALSE)
training_p_2 <- f2_2[ inTraining_p_2,]
testing_p_2  <- f2_2[-inTraining_p_2,]
```

```{r}
#Group 3
set.seed(20140501)
inTraining_p_3 <- createDataPartition(f2_3$samesource, p = .80, list = FALSE)
training_p_3 <- f2_3[ inTraining_p_3,]
testing_p_3  <- f2_3[-inTraining_p_3,]


```

```{r}
#Model1 Group 1
fitControl_v1 <- trainControl(## 10-fold CV
                           method ='repeatedcv',
                           number = 10,
                           repeats = 3,
                           search = 'random')

mtry <- sqrt(ncol(training_p))
tunegrid <- expand.grid(.mtry=mtry)
model_v1 <- train(as.factor(samesource) ~ ccf
                 +rough_cor
                 +D
                 +sd_D
                 +matches
                 +mismatches
                 +cms+non_cms
                 +sum_peaks, 
                 data = training_p, 
                 method = "rf",
                 tuneLength = 15,
                 trControl = fitControl_v1)

print(model_v1)

rf_pred_v1 <- predict(model_v1, testing_p)
confusionMatrix(rf_pred_v1, as.factor(testing_p$samesource))


```

```{r}

#Model1 Group 2
fitControl_v1 <- trainControl(## 10-fold CV
                           method ='repeatedcv',
                           number = 10,
                           repeats = 3,
                           search = 'random')

mtry <- sqrt(ncol(training_p_2))
tunegrid <- expand.grid(.mtry=mtry)
model_v2 <- train(as.factor(samesource) ~ ccf
                 +rough_cor
                 +D
                 +sd_D
                 +matches
                 +mismatches
                 +cms+non_cms
                 +sum_peaks, 
                 data = training_p_2, 
                 method = "rf",
                 tuneLength = 15,
                 trControl = fitControl_v1)

print(model_v2)

rf_pred_v2 <- predict(model_v2, testing_p_2)
confusionMatrix(rf_pred_v2, as.factor(testing_p_2$samesource))

```

```{r}

#Model1 Group 2
fitControl_v1 <- trainControl(## 10-fold CV
                           method ='repeatedcv',
                           number = 10,
                           repeats = 3,
                           search = 'random')

mtry <- sqrt(ncol(training_p_3))
tunegrid <- expand.grid(.mtry=mtry)
model_v3 <- train(as.factor(samesource) ~ ccf
                 +rough_cor
                 +D
                 +sd_D
                 +matches
                 +mismatches
                 +cms+non_cms
                 +sum_peaks, 
                 data = training_p_3, 
                 method = "rf",
                 tuneLength = 15,
                 trControl = fitControl_v1)

print(model_v3)

rf_pred_v3 <- predict(model_v3, testing_p_3)
confusionMatrix(rf_pred_v3, as.factor(testing_p_3$samesource))

```


Let's see how this model performs with a group_2

```{r}

rf_pred_try <- predict(model_v1, testing_p_2)
confusionMatrix(rf_pred_try, as.factor(testing_p$samesource))

```